service: beerschema-hops-api

custom:
  defaultRegion: us-east-1
  settings:
    awsRegion: ${self:provider.region}
    hopsTableName: beerschema-hops-table-${self:provider.stage}
    serviceName: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  profile: blserverless
  region: ${opt:region, self:custom.defaultRegion}
  memorySize: 512
  timeout: 10
  environment: ${self:custom.settings}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.hopsTableName}"
    - Effect: "Allow"
      Action:
        - "cloudfront:updateDistribution"
      Resource:
        - "*"

functions:
  createHop:
    handler: handler.createHop
    events:
      - http:
          path: hops
          method: post
  listHops:
    handler: handler.listHops
    events:
      - http:
          method: get
          path: hops
  getHop:
    handler: handler.getHop
    events:
      - http:
          method: get
          path: hops/{id}
  updateHop:
    handler: handler.updateHop
    events:
      - http:
          method: put
          path: hops/{id}
  deleteHop:
    handler: handler.deleteHop
    events:
      - http:
          method: delete
          path: hops/{id}

resources:
  Resources:
    BeerSchemaHopsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.hopsTableName}
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

# TODO: domain
package:
  exclude:
    - .eslintignore
    - .eslintrc
    - .npmrc
    - .gitignore
    - jasmine.json
    - LICENSE
    - README.md
    - mocks
    - pkg
